packages:
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.11.0
  '@babel/core': ^7.26.10
  '@babel/types': ^7.27.0
  '@types/babel-plugin-macros': ^3.1.3
  '@types/babel__core': ^7.20.5
  '@types/node': ^22.13.13
  '@unocss/core': ^66.0.0
  babel-plugin-macros: ^3.1.0
  bumpp: ^10.1.0
  eslint: ^9.23.0
  image-size: ^2.0.1
  unbuild: ^3.5.0
  vitest: ^3.0.9
